# Variables

SUBNET = "10.10.6." # Attack Lab Subnet
GW = SUBNET + "1"
DC = SUBNET + "100"
BDC = SUBNET + "101"
IIS = SUBNET + "102"
WIN10A = SUBNET + "110"

# Start Config
Vagrant.configure("2") do |config|

  config.vm.define "dc" do |cfg|
    cfg.vm.box = "../Boxes/windows_2016_virtualbox.box" # May be different based on the ESXi setup
    cfg.vm.hostname = "dc"
    cfg.vm.boot_timeout = 600
    # use the plaintext WinRM transport and force it to use basic authentication.
    # NB this is needed because the default negotiate transport stops working
    #    after the domain controller is installed.
    #    see https://groups.google.com/forum/#!topic/vagrant-up/sZantuCM0q4
    cfg.winrm.transport = :plaintext
    cfg.vm.communicator = "winrm"
    cfg.winrm.basic_auth_only = true
    cfg.winrm.timeout = 300
    cfg.winrm.retry_limit = 20
    cfg.vm.network :private_network, ip: DC, gateway: GW

    cfg.vm.provision "shell", path: "scripts/fix-second-network.ps1", privileged: false, args: DC
    cfg.vm.provision "shell", path: "scripts/provision.ps1", privileged: false
    cfg.vm.provision "reload"
    cfg.vm.provision "shell", path: "scripts/provision.ps1", privileged: false
    #cfg.vm.provision "shell", path: "scripts/install-utilities.ps1", privileged: true
    #cfg.vm.provision "shell", path: "scripts/install-sysinternals.ps1", privileged: true
    cfg.vm.provision "file", source: "data/users.csv", destination: "C:/temp/users.csv"
    cfg.vm.provision "shell", path: "scripts/create-ad-users.ps1", privileged: true
    cfg.vm.provision "shell", path: "scripts/configure-ou.ps1", privileged: true
    cfg.vm.provision "shell", path: "scripts/auto-login.ps1", privileged: true
    cfg.vm.provision "reload" # Restart to auto-login as new user

    cfg.vm.provider "virtualbox" do |vb, override|
      vb.gui = true
      vb.customize ["modifyvm", :id, "--memory", 2048]
      vb.customize ["modifyvm", :id, "--cpus", 2]
      vb.customize ["modifyvm", :id, "--vram", "32"]
      vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
    end
  end

  config.vm.define "bdc" do |cfg|
    cfg.vm.box = "../Boxes/windows_2016_virtualbox.box" # May be different based on the ESXi setup
    cfg.vm.hostname = "bdc"
    cfg.vm.boot_timeout = 600
    # use the plaintext WinRM transport and force it to use basic authentication.
    # NB this is needed because the default negotiate transport stops working
    #    after the domain controller is installed.
    #    see https://groups.google.com/forum/#!topic/vagrant-up/sZantuCM0q4
    cfg.winrm.transport = :plaintext
    cfg.vm.communicator = "winrm"
    cfg.winrm.basic_auth_only = true
    cfg.winrm.timeout = 300
    cfg.winrm.retry_limit = 20
    cfg.vm.network :private_network, ip: BDC, gateway: GW

    cfg.vm.provision "shell", path: "scripts/fix-second-network.ps1", privileged: false, args:  "-ip " + BDC + " -dns " + DC
    cfg.vm.provision "shell", path: "scripts/provision.ps1", privileged: false
    cfg.vm.provision "reload"
    cfg.vm.provision "shell", path: "scripts/provision.ps1", privileged: true
    #cfg.vm.provision "shell", path: "scripts/install-utilities.ps1", privileged: true
    #cfg.vm.provision "shell", path: "scripts/install-sysinternals.ps1", privileged: true
    cfg.vm.provision, "shell", path: "scripts/auto-login.ps1", privileged: true
    cfg.vm.provision "reload"

    cfg.vm.provider "virtualbox" do |vb, override|
      vb.gui = true
      vb.customize ["modifyvm", :id, "--memory", 2048]
      vb.customize ["modifyvm", :id, "--cpus", 2]
      vb.customize ["modifyvm", :id, "--vram", "32"]
      vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
    end
  end

  config.vm.define "server-iis" do |cfg|
    cfg.vm.box = "../Boxes/windows_2016_virtualbox.box" # May be different based on the ESXi setup
    cfg.vm.hostname = "server-iis"
    cfg.vm.boot_timeout = 600
    # use the plaintext WinRM transport and force it to use basic authentication.
    # NB this is needed because the default negotiate transport stops working
    #    after the domain controller is installed.
    #    see https://groups.google.com/forum/#!topic/vagrant-up/sZantuCM0q4
    cfg.winrm.transport = :plaintext
    cfg.vm.communicator = "winrm"
    cfg.winrm.basic_auth_only = true
    cfg.winrm.timeout = 300
    cfg.winrm.retry_limit = 20
    cfg.vm.network :private_network, ip: IIS, gateway: GW

    cfg.vm.provision "shell", path: "scripts/fix-second-network.ps1", privileged: false, args:  "-ip " + IIS + " -dns " + DC
    cfg.vm.provision "shell", path: "scripts/provision.ps1", privileged: false
    cfg.vm.provision "reload"
    cfg.vm.provision "shell", path: "scripts/provision.ps1", privileged: false
    #cfg.vm.provision "shell", path: "scripts/install-utilities.ps1", privileged: true
    #cfg.vm.provision "shell", path: "scripts/install-sysinternals.ps1", privileged: true
    cfg.vm.provision "shell", path: "scripts/install-iis.ps1", privileged: true

    cfg.vm.provider "virtualbox" do |vb, override|
      vb.gui = true
      vb.customize ["modifyvm", :id, "--memory", 2048]
      vb.customize ["modifyvm", :id, "--cpus", 2]
      vb.customize ["modifyvm", :id, "--vram", "32"]
      vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
    end
  end  

  config.vm.define "win10" do |cfg|
    cfg.vm.box = "../Boxes/windows_10_virtualbox.box"
    cfg.vm.hostname = "win10"
    cfg.vm.communicator = "winrm"
    cfg.winrm.basic_auth_only = true
    cfg.winrm.timeout = 300
    cfg.winrm.retry_limit = 20
    cfg.vm.network :private_network, ip: WIN10A, gateway: GW, dns: DC

    cfg.vm.provision "shell", path: "scripts/fix-second-network.ps1", privileged: false, args: "-ip " + WIN10A + " -dns " + DC
    cfg.vm.provision "shell", path: "scripts/provision.ps1", privileged: false
    cfg.vm.provision "reload"
    cfg.vm.provision "shell", path: "scripts/provision.ps1", privileged: false
    cfg.vm.provision "shell", path: "scripts/MakeWindows10GreatAgain.ps1", privileged: true
    cfg.vm.provision "shell", path: "scripts/install-utilities.ps1", privileged: true
    cfg.vm.provision "shell", path: "scripts/install-sysinternals.ps1", privileged: true

    cfg.vm.provider "virtualbox" do |vb, override|
      vb.gui = true
      vb.customize ["modifyvm", :id, "--memory", 2048]
      vb.customize ["modifyvm", :id, "--cpus", 2]
      vb.customize ["modifyvm", :id, "--vram", "32"]
      vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
    end
  end
end
